server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/i_tag?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Zhoumiao1314520!

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
